require: rubocop-performance

inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - config/**/*.rb

Style/MixinUsage:
  Exclude:
    - bin/*

Style/StringLiterals:
  EnforcedStyle: double_quotes
