default: &default
  adapter: postgresql
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  user: <%= ENV.fetch("DATABASE_USER") { "prowadzacy_roku" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "prowadzacy_roku" } %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prowadzacy_roku_development

test:
  <<: *default
  database: prowadzacy_roku_test

production:
  <<: *default
  database: prowadzacy_roku_production
